import csv

#Players:::
carltonpl = ["Marc","Murphy","MarcMurphy","MurphyMarc","Bryce","Gibbs","BryceGibbs","GibbsBryce","Kade","Simpson","KadeSimpson","SimpsonKade","Sam","Docherty","SamDocherty","DochertySam","Andrew","Carrazzo","AndrewCarrazzo","CarrazzoAndrew","Tom","Bell","TomBell","BellTom","Chris","Judd","ChrisJudd","JuddChris","Andrew","Walker","AndrewWalker","WalkerAndrew","Andrejs","Everitt","AndrejsEveritt","EverittAndrejs","Patrick","Cripps","PatrickCripps","CrippsPatrick","Zach","Tuohy","ZachTuohy","TuohyZach","Edward","Curnow","EdwardCurnow","CurnowEdward","Christopher","Yarran","ChristopherYarran","YarranChristopher","Levi","Casboult","LeviCasboult","CasboultLevi","Dennis","Armfield","DennisArmfield","ArmfieldDennis","Troy","Menzel","TroyMenzel","MenzelTroy","Cameron","Wood","CameronWood","WoodCameron","Lachlan","Henderson","LachlanHenderson","HendersonLachlan","David","Ellard","DavidEllard","EllardDavid","Sam","Rowe","SamRowe","RoweSam","Ciaran","Byrne","CiaranByrne","ByrneCiaran","Clem","Smith","ClemSmith","SmithClem","Jason","Tutt","JasonTutt","TuttJason","Michael","Jamison","MichaelJamison","JamisonMichael","Simon","White","SimonWhite","WhiteSimon","Liam","Jones","LiamJones","JonesLiam","Kristian","Jaksch","KristianJaksch","JakschKristian","Dale","Thomas","DaleThomas","ThomasDale",]
geelongpl = ["Joel","Selwood","JoelSelwood","SelwoodJoel","Steven","Motlop","StevenMotlop","MotlopSteven","James","Kelly","JamesKelly","KellyJames","Steve","Johnson","SteveJohnson","JohnsonSteve","Corey","Enright","CoreyEnright","EnrightCorey","Cameron","Guthrie","CameronGuthrie","GuthrieCameron","Jackson","Thurlow","JacksonThurlow","ThurlowJackson","Mark","Blicavs","MarkBlicavs","BlicavsMark","Harry","Taylor","HarryTaylor","TaylorHarry","George","Horlin-Smith","GeorgeHorlin-Smith","Horlin-SmithGeorge","Josh","Caddy","JoshCaddy","CaddyJosh","Mathew","Stokes","MathewStokes","StokesMathew","Mitchell","Duncan","MitchellDuncan","DuncanMitchell","Andrew","Mackie","AndrewMackie","MackieAndrew","Jimmy","Bartel","JimmyBartel","BartelJimmy","Darcy","Lang","DarcyLang","LangDarcy","Billie","Smedts","BillieSmedts","SmedtsBillie","Cory","Gregson","CoryGregson","GregsonCory","Tom","Lonergan","TomLonergan","LonerganTom","Mitchell","Clark","MitchellClark","ClarkMitchell","Rhys","Stanley","RhysStanley","StanleyRhys","Jared","Rivers","JaredRivers","RiversJared","Joshua","Walker","JoshuaWalker","WalkerJoshua","Jed","Bews","JedBews","BewsJed","Tom","Hawkins","TomHawkins","HawkinsTom","Jordan","Murdoch","JordanMurdoch","MurdochJordan","Dawson","Simpson","DawsonSimpson","SimpsonDawson","Nakia","Cockatoo","NakiaCockatoo","CockatooNakia"]
fremantlepl = ["Nathan","Fyfe","NathanFyfe","FyfeNathan","David","Mundy","DavidMundy","MundyDavid","Lachie","Neale","LachieNeale","NealeLachie","Stephen","Hill","StephenHill","HillStephen","Michael","Barlow","MichaelBarlow","BarlowMichael","Danyle","Pearce","DanylePearce","PearceDanyle","Michael","Johnson","MichaelJohnson","JohnsonMichael","Paul","Duffield","PaulDuffield","DuffieldPaul","Thomas","Sheridan","ThomasSheridan","SheridanThomas","Garrick","Ibbotson","GarrickIbbotson","IbbotsonGarrick","Matthew","Pavlich","MatthewPavlich","PavlichMatthew","Clancee","Pearce","ClanceePearce","PearceClancee","Lee","Spurr","LeeSpurr","SpurrLee","Luke","McPharlin","LukeMcPharlin","McPharlinLuke","Nicholas","Suban","NicholasSuban","SubanNicholas","Michael","Walters","MichaelWalters","WaltersMichael","Cameron","Sutcliffe","CameronSutcliffe","SutcliffeCameron","Christopher","Mayne","ChristopherMayne","MayneChristopher","Hayden","Ballantyne","HaydenBallantyne","BallantyneHayden","Aaron","Sandilands","AaronSandilands","SandilandsAaron","Zachary","Clarke","ZacharyClarke","ClarkeZachary","Matthew","Taberner","MatthewTaberner","TabernerMatthew","Matthew","De","Boer","MatthewDe","MatthewBoer","DeMatthew","DeBoer","BoerMatthew","BoerDe","MatthewDeBoer","MatthewBoerDe","DeMatthewBoer","DeBoerMatthew","BoerMatthewDe","BoerDeMatthew","Hayden","Crozier","HaydenCrozier","CrozierHayden"]
hawkspl = ["Jordan","Lewis","JordanLewis","LewisJordan","Luke","Hodge","LukeHodge","HodgeLuke","Grant","Birchall","GrantBirchall","BirchallGrant","Isaac","Smith","IsaacSmith","SmithIsaac","Billy","Hartung","BillyHartung","HartungBilly","Sam","Mitchell","SamMitchell","MitchellSam","Josh","Gibson","JoshGibson","GibsonJosh","Matthew","Suckling","MatthewSuckling","SucklingMatthew","William","Langford","WilliamLangford","LangfordWilliam","Shaun","Burgoyne","ShaunBurgoyne","BurgoyneShaun","Taylor","Duryea","TaylorDuryea","DuryeaTaylor","Jarryd","Roughead","JarrydRoughead","RougheadJarryd","Bradley","Hill","BradleyHill","HillBradley","Cyril","Rioli","CyrilRioli","RioliCyril","Jonathan","O'Rourke","JonathanO'Rourke","O'RourkeJonathan","Jack","Gunston","JackGunston","GunstonJack","Jonathon","Ceglar","JonathonCeglar","CeglarJonathon","Paul","Puopolo","PaulPuopolo","PuopoloPaul","Brian","Lake","BrianLake","LakeBrian","Luke","Breust","LukeBreust","BreustLuke","Benjamin","Stratton","BenjaminStratton","StrattonBenjamin","Brendan","Whitecross","BrendanWhitecross","WhitecrossBrendan","Liam","Shiels","LiamShiels","ShielsLiam","James","Sicily","JamesSicily","SicilyJames","James","Frawley","JamesFrawley","FrawleyJames","Jed","Anderson","JedAnderson","AndersonJed","Ben","McEvoy","BenMcEvoy","McEvoyBen"]
stkildapl = ["David","Armitage","DavidArmitage","ArmitageDavid","Jack","Steven","JackSteven","StevenJack","Adam","Schneider","AdamSchneider","SchneiderAdam","Leigh","Montagna","LeighMontagna","MontagnaLeigh","Shane","Savage","ShaneSavage","SavageShane","Sam","Fisher","SamFisher","FisherSam","Jack","Newnes","JackNewnes","NewnesJack","Luke","Dunstan","LukeDunstan","DunstanLuke","Dylan","Roberton","DylanRoberton","RobertonDylan","Jack","Billings","JackBillings","BillingsJack","Sean","Dempster","SeanDempster","DempsterSean","Jarryn","Geary","JarrynGeary","GearyJarryn","Nick","Riewoldt","NickRiewoldt","RiewoldtNick","Maverick","Weller","MaverickWeller","WellerMaverick","Cameron","Shenton","CameronShenton","ShentonCameron","Thomas","Curren","ThomasCurren","CurrenThomas","Jack","Sinclair","JackSinclair","SinclairJack","Josh","Bruce","JoshBruce","BruceJosh","Tim","Membrey","TimMembrey","MembreyTim","Jack","Loniev","JackLonie","LonieJack","Nathan","Wright","NathanWright","WrightNathan","Patrick","McCartin","PatrickMcCartin","McCartinPatrick","Billy","Longer","BillyLonger","LongerBilly","Luke","Delaney","LukeDelaney","DelaneyLuke","Ahmed","Saad","AhmedSaad","SaadAhmed","Eli","Templeton","EliTempleton","TempletonEli"]
collingwoodpl = ["Dane","Swan","DaneSwan","SwanDane","Scott","Pendlebury","ScottPendlebury","PendleburyScott","Taylor","Adams","TaylorAdams","AdamsTaylor","Tom","Langdon","TomLangdon","LangdonTom","Timothy","Broomhead","TimothyBroomhead","BroomheadTimothy","Adam","Oxley","AdamOxley","OxleyAdam","Jarryd","Blair","JarrydBlair","BlairJarryd","Steele","Sidebottom","SteeleSidebottom","SidebottomSteele","Jack","Crisp","JackCrisp","CrispJack","Jackson","Ramsay","JacksonRamsay","RamsayJackson","Brodie","Grundy","BrodieGrundy","GrundyBrodie","Sam","Dwyer","SamDwyer","DwyerSam","Paul","Seedsman","PaulSeedsman","SeedsmanPaul","Travis","Varcoe","TravisVarcoe","VarcoeTravis","Marley","Williams","MarleyWilliams","WilliamsMarley","Jamie","Elliott","JamieElliott","ElliottJamie","Jesse","White","JesseWhite","WhiteJesse","Travis","Cloke","TravisCloke","ClokeTravis","Alan","Toovey","AlanToovey","TooveyAlan","Alex","Fasolo","AlexFasolo","FasoloAlex","Tyson","Goldsack","TysonGoldsack","GoldsackTyson","Ben","Sinclair","BenSinclair","SinclairBen","Nathan","Brown","NathanBrown","BrownNathan","Patrick","Karnezis","PatrickKarnezis","KarnezisPatrick","Corey","Gault","CoreyGault","GaultCorey","Jack","Frost","JackFrost","FrostJack","Jordan","De","Goey","JordanDe","JordanGoey","DeJordan","DeGoey","GoeyJordan","GoeyDe","JordanDeGoey","JordanGoeyDe","DeJordanGoey","DeGoeyJordan","GoeyJordanDe","GoeyDeJordan"]
essendonpl = ["Jobe","Watson","JobeWatson","WatsonJobe","Dyson","Heppell","DysonHeppell","HeppellDyson","Brendon","Goddard","BrendonGoddard","GoddardBrendon","Michael","Hurley","MichaelHurley","HurleyMichael","Brent","Stanton","BrentStanton","StantonBrent","Cale","Hooker","CaleHooker","HookerCale","Jake","Melksham","JakeMelksham","MelkshamJake","Michael","Hibberd","MichaelHibberd","HibberdMichael","Zachary","Merrett","ZacharyMerrett","MerrettZachary","David","Zaharakis","DavidZaharakis","ZaharakisDavid","Dustin","Fletcher","DustinFletcher","FletcherDustin","Travis","Colyer","TravisColyer","ColyerTravis","Martin","Gleeson","MartinGleeson","GleesonMartin","Mark","Baguley","MarkBaguley","BaguleyMark","Ben","Howlett","BenHowlett","HowlettBen","Adam","Cooney","AdamCooney","CooneyAdam","Patrick","Ambrose","PatrickAmbrose","AmbrosePatrick","Paul","Chapman","PaulChapman","ChapmanPaul","James","Gwilt","JamesGwilt","GwiltJames","Joe","Daniher","JoeDaniher","DaniherJoe","Tom","Bellchambers","TomBellchambers","BellchambersTom","Jake","Carlisle","JakeCarlisle","CarlisleJake","Jason","Ashby","JasonAshby","AshbyJason","David","Myers","DavidMyers","MyersDavid"]
goldcoastpl = ["Dion","Prestia","DionPrestia","PrestiaDion","Michael","Rischitelli","MichaelRischitelli","RischitelliMichael","Harley","Bennell","HarleyBennell","BennellHarley","Gary","Jnr","Ablett","GaryJnr","GaryAblett","JnrGary","JnrAblett","AblettGary","AblettJnr","GaryJnrAblett","GaryAblettJnr","JnrGaryAblett","JnrAblettGary","AblettGaryJnr","AblettJnrGary","David","Swallow","DavidSwallow","SwallowDavid","Jarrod","Harbrow","JarrodHarbrow","HarbrowJarrod","Mitchell","Hallahan","MitchellHallahan","HallahanMitchell","Adam","Saad","AdamSaad","SaadAdam","Jack","Martin","JackMartin","MartinJack","Trent","McKenzie","TrentMcKenzie","McKenzieTrent","Steven","May","StevenMay","MaySteven","Nick","Malceski","NickMalceski","MalceskiNick","Matt","Shaw","MattShaw","ShawMatt","Kade","Kolodjashnij","KadeKolodjashnij","KolodjashnijKade","Thomas","Lynch","ThomasLynch","LynchThomas","Aaron","Hall","AaronHall","HallAaron","Sean","Lemmens","SeanLemmens","LemmensSean","Greg","Broughton","GregBroughton","BroughtonGreg","Touk","Miller","ToukMiller","MillerTouk","Brandon","Matera","BrandonMatera","MateraBrandon","Zac","Smith","ZacSmith","SmithZac","Sebastian","Tape","SebastianTape","TapeSebastian","Jarrod","Garlett","JarrodGarlett","GarlettJarrod","Daniel","Gorringe","DanielGorringe","GorringeDaniel","Alex","Sexton","AlexSexton","SextonAlex","Rory","Thompson","RoryThompson","ThompsonRory","Sam","Day","SamDay","DaySam"]
adelaidepl = ["Scott","Thompson","ScottThompson","ThompsonScott","Rory","Sloane","RorySloane","SloaneRory","Richard","Douglas","RichardDouglas","DouglasRichard","Patrick","Dangerfield","PatrickDangerfield","DangerfieldPatrick","Brodie","Smith","BrodieSmith","SmithBrodie","Matthew","Jaensch","MatthewJaensch","JaenschMatthew","Cameron","Ellis-Yolmen","CameronEllis-Yolmen","Ellis-YolmenCameron","Rory","Laird","RoryLaird","LairdRory","Ricky","Henderson","RickyHenderson","HendersonRicky","Daniel","Talia","DanielTalia","TaliaDaniel","Tom","Lynch","TomLynch","LynchTom","Taylor","Walker","TaylorWalker","WalkerTaylor","Kyle","Hartigan","KyleHartigan","HartiganKyle","Eddie","Betts","EddieBetts","BettsEddie","David","MacKay","DavidMacKay","MacKayDavid","Kyle","Cheney","KyleCheney","CheneyKyle","Sam","Jacobs","SamJacobs","JacobsSam","Nathan","Van","Berlo","NathanVan","NathanBerlo","VanNathan","VanBerlo","BerloNathan","BerloVan","NathanVanBerlo","NathanBerloVan","VanNathanBerlo","VanBerloNathan","BerloNathanVan","BerloVanNathan","Josh","Jenkins","JoshJenkins","JenkinsJosh","Luke","Brown","LukeBrown","BrownLuke","Jarryd","Lyons","JarrydLyons","LyonsJarryd","Mitchell","Grigg","MitchellGrigg","GriggMitchell","Charlie","Cameron","CharlieCameron","CameronCharlie","Matthew","Wright","MatthewWright","WrightMatthew","Jake","Kelly","JakeKelly","KellyJake"]
westcoastpl = ["Matthew","Priddis","MatthewPriddis","PriddisMatthew","Chris","Masten","ChrisMasten","MastenChris","Andrew","Gaff","AndrewGaff","GaffAndrew","Matthew","Rosa","MatthewRosa","RosaMatthew","Luke","Shuey","LukeShuey","ShueyLuke","Dominic","Sheed","DominicSheed","SheedDominic","Scott","Selwood","ScottSelwood","SelwoodScott","Jeremy","McGovern","JeremyMcGovern","McGovernJeremy","Mark","Lecras","MarkLecras","LecrasMark","Bradley","Sheppard","BradleySheppard","SheppardBradley","Sam","Butler","SamButler","ButlerSam","Shannon","Hurn","ShannonHurn","HurnShannon","Will","Schofield","WillSchofield","SchofieldWill","Sharrod","Wellingham","SharrodWellingham","WellinghamSharrod","Elliot","Yeo","ElliotYeo","YeoElliot","Joshua","Kennedy","JoshuaKennedy","KennedyJoshua","Jamie","Cripps","JamieCripps","CrippsJamie","Nicholas","Naitanui","NicholasNaitanui","NaitanuiNicholas","Jackson","Nelson","JacksonNelson","NelsonJackson","Jamie","Bennell","JamieBennell","BennellJamie","Josh","Hill","JoshHill","HillJosh","Tom","Lamb","TomLamb","LambTom","Simon","Tunbridgev","SimonTunbridge","TunbridgeSimon","Scott","Lycett","ScottLycett","LycettScott","Patrick","McGinnity","PatrickMcGinnity","McGinnityPatrick","Liam","Duggan","LiamDuggan","DugganLiam","Mitchell","Brown","MitchellBrown","BrownMitchell"]
northmelbournepl = ["Sam","Gibson","SamGibson","GibsonSam","Andrew","Swallow","AndrewSwallow","SwallowAndrew","Ben","Cunnington","BenCunnington","CunningtonBen","Brent","Harvey","BrentHarvey","HarveyBrent","Robbie","Tarrant","RobbieTarrant","TarrantRobbie","Ben","Jacobs","BenJacobs","JacobsBen","Shaun","Higgins","ShaunHiggins","HigginsShaun","Luke","McDonald","LukeMcDonald","McDonaldLuke","Nick","Dal","Santo","NickDal","NickSanto","DalNick","DalSanto","SantoNick","SantoDal","NickDalSanto","NickSantoDal","DalNickSanto","DalSantoNick","SantoNickDal","SantoDalNick","Robin","Nahas","RobinNahas","NahasRobin","Jamie","MacMillan","JamieMacMillan","MacMillanJamie","Shaun","Atley","ShaunAtley","AtleyShaun","Ryan","Bastinac","RyanBastinac","BastinacRyan","Samuel","Wright","SamuelWright","WrightSamuel","Todd","Goldstein","ToddGoldstein","GoldsteinTodd","Jack","Ziebell","JackZiebell","ZiebellJack","Mason","Wood","MasonWood","WoodMason","Scott","Thompson","ScottThompson","ThompsonScott","Jarrad","Waite","JarradWaite","WaiteJarrad","Lindsay","Thomas","LindsayThomas","ThomasLindsay","Drew","Petrie","DrewPetrie","PetrieDrew","Michael","Firrito","MichaelFirrito","FirritoMichael","Kayne","Turner","KayneTurner","TurnerKayne","Daniel","Wells","DanielWells","WellsDaniel","Ben","Brown","BenBrown","BrownBen","Joel","Tippett","JoelTippett","TippettJoel"]
portadelaidepl = ["Robbie","Gray","RobbieGray","GrayRobbie","Brad","Ebert","BradEbert","EbertBrad","Oliver","Wines","OliverWines","WinesOliver","Jasper","Pittard","JasperPittard","PittardJasper","Travis","Boak","TravisBoak","BoakTravis","Jared","Polec","JaredPolec","PolecJared","Hamish","Hartlett","HamishHartlett","HartlettHamish","Kane","Cornes","KaneCornes","CornesKane","Chad","Wingard","ChadWingard","WingardChad","Thomas","Jonas","ThomasJonas","JonasThomas","Matthew","Broadbent","MatthewBroadbent","BroadbentMatthew","Aaron","Young","AaronYoung","YoungAaron","Jackson","Trengove","JacksonTrengove","TrengoveJackson","Nathan","Krakouer","NathanKrakouer","KrakouerNathan","Justin","Westhoff","JustinWesthoff","WesthoffJustin","Kane","Mitchell","KaneMitchell","MitchellKane","Angus","Monfries","AngusMonfries","MonfriesAngus","Alipate","Carlile","AlipateCarlile","CarlileAlipate","Jay","Schulz","JaySchulz","SchulzJay","Jake","Neade","JakeNeade","NeadeJake","Matthew","White","MatthewWhite","WhiteMatthew","Patrick","Ryder","PatrickRyder","RyderPatrick","Jack","Hombsch","JackHombsch","HombschJack","Jarman","Impey","JarmanImpey","ImpeyJarman","Jarrad","Redden","JarradRedden","ReddenJarrad","John","Butcher","JohnButcher","ButcherJohn","Brendon","Ah","Chee","BrendonAh","BrendonChee","AhBrendon","AhChee","CheeBrendon","CheeAh","BrendonAhChee","BrendonCheeAh","AhBrendonChee","AhCheeBrendon","CheeBrendonAh","CheeAhBrendon"]
sydneyswanspl = ["Josh","Kennedy","JoshP","JoshKennedy","P.Josh","P.Kennedy","KennedyJosh","KennedyP","JoshP.Kennedy","JoshKennedyP.","P.JoshKennedy","P.KennedyJosh","KennedyJosh","KennedyP.Josh","Daniel","Hannebery","DanielHannebery","HanneberyDaniel","Kieren","Jack","KierenJack","JackKieren","Jarrad","McVeigh","JarradMcVeigh","McVeighJarrad","Luke","Parker","LukeParker","ParkerLuke","Craig","Bird","CraigBird","BirdCraig","Nick","Smith","NickSmith","SmithNick","Heath","Grundy","HeathGrundy","GrundyHeath","Harry","Cunningham","HarryCunningham","CunninghamHarry","Jake","Lloyd","JakeLloyd","LloydJake","Rhyce","Shaw","RhyceShaw","ShawRhyce","Dane","Rampe","DaneRampe","RampeDane","Lewis","Jetta","LewisJetta","JettaLewis","Jeremy","Laidler","JeremyLaidler","LaidlerJeremy","Lance","Franklin","LanceFranklin","FranklinLance","Isaac","Heeney","IsaacHeeney","HeeneyIsaac","Ben","McGlynn","BenMcGlynn","McGlynnBen","Gary","Rohan","GaryRohan","RohanGary","Dean","Towers","DeanTowers","TowersDean","Sam","Reid","SamReid","ReidSam","Ted","Richards","TedRichards","RichardsTed","Mike","Pyke","MikePyke","PykeMike","Kurt","Tippett","KurtTippett","TippettKurt","Adam","Goodes","AdamGoodes","GoodesAdam"]
richmondtigerspl = ["Trent","Cotchin","TrentCotchin","CotchinTrent","Anthony","Miles","AnthonyMiles","MilesAnthony","Brandon","Ellis","BrandonEllis","EllisBrandon","Bachar","Houli","BacharHouli","HouliBachar","Dustin","Martin","DustinMartin","MartinDustin","Shane","Edwards","ShaneEdwards","EdwardsShane","Taylor","Hunt","TaylorHunt","HuntTaylor","Shaun","Grigg","ShaunGrigg","GriggShaun","Kamdyn","Mcintosh","KamdynMcintosh","McintoshKamdyn","Brett","Deledio","BrettDeledio","DeledioBrett","Alex","Rance","AlexRance","RanceAlex","Troy","Chaplin","TroyChaplin","ChaplinTroy","Ricky","Petterd","RickyPetterd","PetterdRicky","Nick","Vlastuin","NickVlastuin","VlastuinNick","Jack","Riewoldt","JackRiewoldt","RiewoldtJack","Chris","Newman","ChrisNewman","NewmanChris","Benjamin","Griffiths","BenjaminGriffiths","GriffithsBenjamin","Ivan","Maric","IvanMaric","MaricIvan","Sam","Lloyd","SamLloyd","LloydSam","David","Astbury","DavidAstbury","AstburyDavid","Nathan","Gordon","NathanGordon","GordonNathan","Jake","Batchelor","JakeBatchelor","BatchelorJake","Dylan","Grimes","DylanGrimes","GrimesDylan","Matthew","Arnot","MatthewArnot","ArnotMatthew","Matthew","Mcdonough","MatthewMcdonough","McdonoughMatthew","Steven","Morris","StevenMorris","MorrisSteven","Kane","Lambert","KaneLambert","LambertKane","Nathan","Drummond","NathanDrummond","DrummondNathan","Chris","Knights","ChrisKnights","KnightsChris"]
westernbullpl = ["Matthew","Boyd","MatthewBoyd","BoydMatthew","Jackson","Macrae","JacksonMacrae","MacraeJackson","Luke","Dahlhaus","LukeDahlhaus","DahlhausLuke","Marcus","Bontempelli","MarcusBontempelli","BontempelliMarcus","Robert","Murphy","RobertMurphy","MurphyRobert","Lin","Jong","LinJong","JongLin","Mitchell","Wallis","MitchellWallis","WallisMitchell","Jason","Johannisen","JasonJohannisen","JohannisenJason","Michael","Talia","MichaelTalia","TaliaMichael","Stewart","Crameri","StewartCrameri","CrameriStewart","Nathan","Hrovat","NathanHrovat","HrovatNathan","Easton","Wood","EastonWood","WoodEaston","Koby","Stevens","KobyStevens","StevensKoby","Mitch","Honeychurch","MitchHoneychurch","HoneychurchMitch","Liam","Picken","LiamPicken","PickenLiam","Tory","Dickson","ToryDickson","DicksonTory","Will","Minson","WillMinson","MinsonWill","Jake","Stringer","JakeStringer","StringerJake","Jordan","Roughead","JordanRoughead","RougheadJordan","Lukas","Webb","LukasWebb","WebbLukas","Thomas","Boyd","ThomasBoyd","BoydThomas","Jarrad","Grant","JarradGrant","GrantJarrad","Dale","Morris","DaleMorris","MorrisDale","Brett","Goodes","BrettGoodes","GoodesBrett","Jack","Redpath","JackRedpath","RedpathJack","Ayce","Cordy","AyceCordy","CordyAyce"]
gwsgiantspl = ["Lachie","Whitfield","LachieWhitfield","WhitfieldLachie","Adam","Treloar","AdamTreloar","TreloarAdam","Toby","Greene","TobyGreene","GreeneToby","Callan","Ward","CallanWard","WardCallan","Joshua","Kelly","JoshuaKelly","KellyJoshua","Dylan","Shiel","DylanShiel","ShielDylan","Heath","Shaw","HeathShaw","ShawHeath","Tom","Scully","TomScully","ScullyTom","Devon","Smith","DevonSmith","SmithDevon","Stephen","Coniglio","StephenConiglio","ConiglioStephen","Ryan","Griffen","RyanGriffen","GriffenRyan","Tomas","Bugg","TomasBugg","BuggTomas","Nick","Haynes","NickHaynes","HaynesNick","Rhys","Palmer","RhysPalmer","PalmerRhys","Phil","Davis","PhilDavis","DavisPhil","Shane","Mumford","ShaneMumford","MumfordShane","Cameron","McCarthy","CameronMcCarthy","McCarthyCameron","Joel","Patfull","JoelPatfull","PatfullJoel","Curtly","Hampton","CurtlyHampton","HamptonCurtly","Jeremy","Cameron","JeremyCameron","CameronJeremy","Aidan","Corr","AidanCorr","CorrAidan","Nathan","Wilson","NathanWilson","WilsonNathan","Adam","Tomlinson","AdamTomlinson","TomlinsonAdam","Andrew","Phillips","AndrewPhillips","PhillipsAndrew"]
melbdemonspl = ["Jack","Viney","JackViney","VineyJack","Nathan","Jones","NathanJones","JonesNathan","Daniel","Cross","DanielCross","CrossDaniel","Tom","McDonald","TomMcDonald","McDonaldTom","Viv","Michie","VivMichie","MichieViv","Dom","Tyson","DomTyson","TysonDom","Aaron","Vandenberg","AaronVandenberg","VandenbergAaron","Heritier","Lumumba","HeritierLumumba","LumumbaHeritier","Jeremy","Howe","JeremyHowe","HoweJeremy","Bernie","Vince","BernieVince","VinceBernie","Ben","Newton","BenNewton","NewtonBen","Christian","Salem","ChristianSalem","SalemChristian","Jack","Watts","JackWatts","WattsJack","Jeff","Garlett","JeffGarlett","GarlettJeff","Lynden","Dunn","LyndenDunn","DunnLynden","Colin","Garland","ColinGarland","GarlandColin","Jesse","Hogan","JesseHogan","HoganJesse","Chris","Dawes","ChrisDawes","DawesChris","Jay","Kennedy-Harris","JayKennedy-Harris","Kennedy-HarrisJay","Angus","Brayshaw","AngusBrayshaw","BrayshawAngus","Neville","Jetta","NevilleJetta","JettaNeville","Dean","Kent","DeanKent","KentDean","Sam","Frost","SamFrost","FrostSam","Mark","Jamar","MarkJamar","JamarMark","Jimmy","Toumpas","JimmyToumpas","ToumpasJimmy"]
brisblionspl = ["Dayne","Beams","DayneBeams","BeamsDayne","Daniel","Rich","DanielRich","RichDaniel","Dayne","Zorko","DayneZorko","ZorkoDayne","Jack","Redden","JackRedden","ReddenJack","Mitch","Robinson","MitchRobinson","RobinsonMitch","Allen","Christensen","AllenChristensen","ChristensenAllen","Tom","Rockliff","TomRockliff","RockliffTom","Marco","Paparone","MarcoPaparone","PaparoneMarco","James","Aish","JamesAish","AishJames","Stefan","Martin","StefanMartin","MartinStefan","Jed","Adcock","JedAdcock","AdcockJed","Claye","Beams","ClayeBeams","BeamsClaye","Lewis","Taylor","LewisTaylor","TaylorLewis","Daniel","Merrett","DanielMerrett","MerrettDaniel","Rohan","Bewick","RohanBewick","BewickRohan","Zac","O'Brien","ZacO'Brien","O'BrienZac","Joshua","Green","JoshuaGreen","GreenJoshua","Jaden","McGrath","JadenMcGrath","McGrathJaden","Justin","Clarke","JustinClarke","ClarkeJustin","Ryan","Lester","RyanLester","LesterRyan","Darcy","Gardiner","DarcyGardiner","GardinerDarcy","Harris","Andrews","HarrisAndrews","AndrewsHarris","Matthew","Maguire","MatthewMaguire","MaguireMatthew","Daniel","McStay","DanielMcStay","McStayDaniel","Matthew","Leuenberger","MatthewLeuenberger","LeuenbergerMatthew","Sam","Mayes","SamMayes","MayesSam","Brent","Staker","BrentStaker","StakerBrent","Michael","Close","MichaelClose","CloseMichael"]

#Teams:::
brisbane = ["afllions","aflbrisbane","brisbanefc","brisbanefootball","brisbane_fc","thelions","brisbanelions","brisbaneftw","brisbanerule","lionsftw","lionsrule","golions","gobrisbane","lionssuck","brisbanesuck"]
goldcoast = ["aflsuns","aflgoldcoast","goldcoastfootball","goldcoastfc","goldcoast_fc","thesuns","sunssuck","goldcoastsuck","gosuns","sunsrule","gogoldcoast","goldcoastrule","sunsftw","goldcoastftw"]
collingwood = ["collingwood_fc","collingwoodfc","aflpies","aflmagpies","aflcollingwood","collingwoodfootball","collingwoodpies","gocollingwood","collingwoodsuck","magpiesrule","magpies","gomagpies","magpiessuck","piessuck","gopies","magpiesftw","piesftw","piesrule","thepies"]
geelong = ["aflcats","aflgeelong","geelongfootball","geelongfc","geelong_fc","geelongcats","gogeelong","geelongsuck","geelongrule","thecats","gocats","catssuck"]
richmond = ["afltigers","aflrichmond","richmondfootball","richmondtigers","richmondfc","richmond_fc","gorichmond","richmondftw","richmondsuck","richmondrule","tigerssuck","tigersftw","tigersrule","thetigers"]
northmelb = ["aflkanga","aflnorth","northmelbournefootball","northmelbournefc","northmelbourne_fc","gonorthmelbourne","gonorth","northftw","northmelbourneftw","northmelbournerule","northmelbornesuck","thekangaroos","gokangaroo","kangaroosftw","kangaroosrule","kangaroossuck"]
westernbulldogs =["afldogs","aflbulldogs","aflwesternbulldogs","footscrayfootball","westernbulldogs","footscrayfc","footscray_fc","gofootscray","gowesternbulldogs","gobulldogs","bulldogsftw","footscrayftw","westernbulldogsftw","westernbulldogsrule","bulldogsrule","bulldogssuck"]
stkilda = ["stkildafc","stkilda_fc","stkildafootball","stkildafootball","aflstkilda","aflkilda","aflsaint","aflthesaints","gostkilda","gosaints","gokilda","stkildaftw","saintsftw","saintsrule","kildarule","kildasuck","saintssuck","thesaints"]
essendon =[ "afldon","aflbomber","aflessendon","essendonfootball","essendonfc","essendon_fc","goessendon","gobombers","godons","essendonftw","bombersftw","donsftw","essendonrule","bombersrule","donsrule","bomberssuck","donssuck","essendonsuck","thedons","thebombers"]
sydney = ["aflswans","sydneyswans","theswans","swansrule","swanssuck","aflsydneyswans","goswans","sydneyswansftw","swansftw"]
carlton = ["aflblues","aflcarlton","carltonfootball","carltonblues","carltonfc","carlton_fc","gocarlton","carltonftw","carltonsuck","carltonrule","goblues","bluessuck"]
goldcoast = ["aflsuns","aflgoldcoast","goldcoastfootball","goldcoastfc","goldcoast_fc","thesuns","sunssuck","goldcoastsuck","gosuns","sunsrule","gogoldcoast","goldcoastrule","sunsftw","goldcoastftw"]
brisbane = ["afllions","aflbrisbane","brisbanefc","brisbanefootball","brisbane_fc","thelions","brisbanelions","brisbaneftw","brisbanerule","lionsftw","lionsrule","golions","gobrisbane","lionssuck","brisbanesuck"]
hawthorn = ["aflhawthorn","aflhawk","aflhawks","hawthornhawks","hawthornfootball","hawthornfc","hawthorn_fc","gohawks","gohawthorn","hawksftw","thehawks","hawthornftw","hawksrule","hawthornrule","hawthornsuck","hawkssuck"]
westcoast = ["westcoastfootball","westcoastfc","westcoast_fc","afleagles","aflwestcoast","westcoasteagles","goeagles","gowestcoast","eaglesftw","westcoastftw","westcoastrule","eaglesrule","eaglessuck","westcoastsuck"]
gwsgiants = ["aflgiant","giantsfc","gws_fc","gwsfc","giants_fc","aflgwsgiant","gwsgiant","thegiants","greaterwesternsydney","gogiants","gogwsgiants","giantsftw","giantsrule","gwsrule","giantssuck","gwssuck","aflgws"]
melbourne = ["afldemon","afldee","melbournefootball","melbournefc","melbourne_fc","godemon","godee","demonsftw","deesftw","deessuck","deesrule","demonssuck","thedemons"]
fremantle = ["afldocker","aflfreo","aflfremantle","fremantlefootballclub","fremantlefc","fremantle_fc","gofremantle","gofreo","fremantleftw","fremantlesuck","fremantlerule","freosftw","freossuck","freosrule","dockersftw","dockersrule","dockerssuck","godockers","dockers"]
adelaide = ["afladelaide","aflcrow","adelaidefootball","adelaidefc","adelaide_fc","goadelaide","gocrow","adelaideftw","crowsftw","adelaiderule","crowsrule","adelaidesuck","crowssuck"]
portadelaide = ["aflportadelaide","aflport", "aflpower","pafc","portadelaidefootball","portadelaidefc","portadelaide_fc","goportadelaide","gopower","portadelaideftw","powersftw","portadelaiderule","powersrule","portadelaidesuck","powerssuck"] 


pos = 0
neg = 0
pos2 = 0
neg2 = 0
neut = 0
neut2 = 0
count1 = 0
count2 = 0 
#start process_tweet
def team1Tweet(tweet):
    '''process the tweets'''
    i = 0
    for t in brisbane:
        if(t in tweet):
            i = i+1
    for p in brisblionspl:
        if(p in tweet):
            i = i+1   

    return i
#end

#start replaceTwoOrMore
def team2Tweet(tweet):
    j = 0
    for t in goldcoast:
        if(t in tweet):
            j = j+1
    for p in goldcoastpl:
        if(p in tweet):
            j = j+1   

    return j
#end
    
#end

try:
    fRead = csv.reader(open('I:\\RP\\goldcoastvsbrisbaneResult.csv',"rU"),dialect='excel-tab') # delimiter = '',quotechar = ':',doublequote=True) #
    fWrite = open('I:\\RP\\brisbane.csv',"w")
    fWrite2 = open('I:\\RP\\goldcoast.csv',"w")
    fWrite3 = open('I:\\RP\\lionsvssunsSTAT.csv',"w")
except IOError, message: 
    print "File could not be opened:",message



for row in fRead:
    try:
        sentiment = row[0]
        tweet = row[1]
        print(tweet)
    except IndexError, message:
        print" row:", message
        continue
    
    val1 = team1Tweet(tweet)
    val2 = team2Tweet(tweet)
    if(val1>val2):
        if("negative" in sentiment):
            neg = neg+1
        elif("positive" in sentiment):
            pos = pos+1
        else:
            neut = neut+1
        
        count1 = count1 +1
        print >> fWrite,'|%s|' %(row)
        
    else:
        if("negative" in sentiment):
            neg2 = neg2+1
        elif("positive" in sentiment):
            pos2 = pos2+1
        else:
            neut2 = neut2+1
                
        count2 = count2 +1
        print >> fWrite2,'|%s|' %(row)
 
brisbstats2 = "BRISBANE-LIONS Stats:"
brisbstats3 = "Tweet Count:::"+str(count1) 
brisbStats = "BRISBANE-LIONS Sentiments::: "+"   Positives :"+str(pos)+"  Negatives:"+str(neg)+"  Neutral:"+str(neut)
    
goldstats2 = "GOLDCOAST-SUNS Stats:"
goldstats3 = "Tweet Count:::"+str(count2)
goldStats = "GOLDCOAST-SUNS Sentiments::: "+"   Positives :"+str(pos2)+"  Negatives:"+str(neg2)+"  Neutral:"+str(neut2)
print >> fWrite3,'|%s|' %(brisbstats2)
print >> fWrite3
print >> fWrite3,'|%s|' %(brisbstats3)
print >> fWrite3
print >> fWrite3,'|%s|' %(brisbStats)
print >> fWrite3
print >> fWrite3,'|%s|' %(goldstats2)
print >> fWrite3
print >> fWrite3,'|%s|' %(goldstats3)
print >> fWrite3
print >> fWrite3,'|%s|' %(goldStats)
print >> fWrite3    
fWrite.close()
fWrite2.close()
fWrite3.close()
#end loop


